### PR TITLE
fix

### PR DESCRIPTION
**Pull request by AlexanderNaumov**

### CODE REVIEW

**Comment by VyacheslavAcronis** [comment]
That's right. Please write your email.

**Comment by AlexanderNaumov** [comment]
a.naumov@mygento.ru

**Comment by chezzdev** [comment]
Does anyone know any active discussions on this bug and ways to fix it? I've found only https://bugs.swift.org/browse/SR-7048.

**Comment by VyacheslavAcronis** [comment]
@AlexanderNaumov Please read your email.

**Pull request closed without merging**
